Exception in thread Exception in Tkinter callbackToggles
:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/spartans/Downloads/Bomb-Project-main/bomb_phases.py", line 328, in run
    phase = self._phase_map[name]
  Traceback (most recent call last):
   File "/usr/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.11/tkinter/__init__.py", line 861, in callit
    func(*args)
   File "/home/spartans/Downloads/Bomb-Project-main/bomb.py", line 27, in bootup
    check_phases()
   File "/home/spartans/Downloads/Bomb-Project-main/bomb.py", line 126, in check_phases
    gui._ltoggles["text"] = f"Toggles: {toggles}"
                            ^^^^^^^^^^^^^^^^^^^^^
 TypeError: __str__ returned non-string (type NoneType)
                    ^^^^
NameError: name 'name' is not defined. Did you mean: 'Frame'?
